---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-1
  namespace: postgres
  labels:
    app: postgres
spec:
  volumeMode: Filesystem
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce # смонтирован на чтение и запись к одному поду
  persistentVolumeReclaimPolicy: Retain  # Retain = pv удален не будет
  storageClassName: local-storage
  local:
    fsType: ext4
    path: /mnt/local-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube # название ноды, где располагается хранилище