---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
        - name: redmine
          image: redmine:4.1.1
          ports:
            - containerPort: 3000
          env:
            - name: REDMINE_DB_POSTGRES
              value: postgres
            - name: REDMINE_DB_USERNAME
              value: testuser
            - name: REDMINE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: postgre-pass
                  optional: false
            - name: REDMINE_DB_DATABASE
              value: testdatabase
            - name: REDMINE_SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: redmine
                  key: redmine-pass
                  optional: false